### ISSUE TITLE
Hex code field not allowing input and editing.

### ISSUE THREAD

**Issue by chadleylyell** [hbang/Alderis#12] opened 2020-07-19 14:25 UTC
On any tweak that uses Alderis, I am unable to edit the hex code text field. I have tried reinstalling and even downgrading Alderis. I try highlighting the whole text field and typing, but nothing changes. The only way to change it is with the sliders, which is difficult sometimes. But the RGB input fields work....

**Comment by kirb** [comment] 2020-07-19 14:26
Duplicate of #2. Fix hasn’t been released yet, sorry.

**Closed by kirb** 2020-07-19 14:26 UTC
